/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as OnboardingWorkerRouteImport } from './routes/onboarding.worker'
import { Route as OnboardingSeekerRouteImport } from './routes/onboarding.seeker'
import { Route as OnboardingRoleRouteImport } from './routes/onboarding.role'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWorkerRoute = OnboardingWorkerRouteImport.update({
  id: '/onboarding/worker',
  path: '/onboarding/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSeekerRoute = OnboardingSeekerRouteImport.update({
  id: '/onboarding/seeker',
  path: '/onboarding/seeker',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoleRoute = OnboardingRoleRouteImport.update({
  id: '/onboarding/role',
  path: '/onboarding/role',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/onboarding/seeker': typeof OnboardingSeekerRoute
  '/onboarding/worker': typeof OnboardingWorkerRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/onboarding/seeker': typeof OnboardingSeekerRoute
  '/onboarding/worker': typeof OnboardingWorkerRoute
  '/onboarding': typeof OnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding/role': typeof OnboardingRoleRoute
  '/onboarding/seeker': typeof OnboardingSeekerRoute
  '/onboarding/worker': typeof OnboardingWorkerRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding/role'
    | '/onboarding/seeker'
    | '/onboarding/worker'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding/role'
    | '/onboarding/seeker'
    | '/onboarding/worker'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/onboarding/role'
    | '/onboarding/seeker'
    | '/onboarding/worker'
    | '/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoleRoute: typeof OnboardingRoleRoute
  OnboardingSeekerRoute: typeof OnboardingSeekerRoute
  OnboardingWorkerRoute: typeof OnboardingWorkerRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/worker': {
      id: '/onboarding/worker'
      path: '/onboarding/worker'
      fullPath: '/onboarding/worker'
      preLoaderRoute: typeof OnboardingWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/seeker': {
      id: '/onboarding/seeker'
      path: '/onboarding/seeker'
      fullPath: '/onboarding/seeker'
      preLoaderRoute: typeof OnboardingSeekerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/role': {
      id: '/onboarding/role'
      path: '/onboarding/role'
      fullPath: '/onboarding/role'
      preLoaderRoute: typeof OnboardingRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoleRoute: OnboardingRoleRoute,
  OnboardingSeekerRoute: OnboardingSeekerRoute,
  OnboardingWorkerRoute: OnboardingWorkerRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
